##### Create some test data with mean=0 and stdDev=1.0

In [2]:
rows = 100
cols = 20
tm.N = rows
tm.K = cols

df = tm.makeDataFrame()
x = [x for x in range(rows)]
df.index=x

# Here are the first 5 rows
df.head()

,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T
0,1.096606,-0.263071,1.950228,-0.616639,-0.759178,0.504519,2.467393,0.724955,-0.833960,-1.305027,-0.381730,0.922268,1.272660,0.644595,0.250213,-0.228495,-0.590929,0.066425,-0.891829,-0.775187
1,-1.561886,2.081268,-0.572404,0.410805,0.760514,1.529157,0.657727,0.688868,-0.788486,-0.301661,0.691919,-1.284826,-1.724592,-0.416671,-0.825607,1.312703,1.683499,1.086654,-0.681848,-0.393506
2,0.150929,1.489105,0.774906,0.576417,0.477904,1.727845,0.369705,1.334072,-1.101207,2.503235,-0.420711,-0.942370,-0.089493,-0.469425,-0.772614,0.643430,0.748837,-1.271144,1.059584,1.851139
3,0.784248,-0.021723,0.223220,0.688417,0.650573,-0.566146,0.991747,0.950820,0.773550,0.416433,-0.976000,-0.087550,0.273250,0.000753,-1.344112,-1.103356,1.141593,1.413234,-0.536577,-1.250533
4,1.359370,-2.039269,-0.538055,0.330441,1.155280,-0.258783,0.968644,-0.236284,0.040904,1.197598,-0.164752,-0.612500,-1.165849,1.120324,0.615479,-0.376268,1.202675,1.648090,0.861845,-0.362805

##### Look at the correlation matrix

In [4]:
df.corr()     # Should see nothing higher than about 0.25

,A,B,C,D,E,F,G,H,I,J
A,1.000000,0.055498,0.143128,-0.093236,-0.104172,0.133259,-0.054147,0.232755,-0.055202,-0.037960
B,0.055498,1.000000,0.079135,-0.236071,0.000851,-0.046927,-0.066417,0.199712,0.019713,-0.029974
C,0.143128,0.079135,1.000000,-0.036313,-0.024601,0.039943,0.115229,-0.007398,-0.005359,-0.020846
D,-0.093236,-0.236071,-0.036313,1.000000,0.081851,-0.002982,0.081109,-0.122255,0.097348,-0.059413
E,-0.104172,0.000851,-0.024601,0.081851,1.000000,-0.016798,-0.059044,0.016423,0.092680,-0.067127
F,0.133259,-0.046927,0.039943,-0.002982,-0.016798,1.000000,0.066916,-0.095933,-0.172330,-0.040007
G,-0.054147,-0.066417,0.115229,0.081109,-0.059044,0.066916,1.000000,0.027569,0.098738,-0.185572
H,0.232755,0.199712,-0.007398,-0.122255,0.016423,-0.095933,0.027569,1.000000,0.079860,-0.132020
I,-0.055202,0.019713,-0.005359,0.097348,0.092680,-0.172330,0.098738,0.079860,1.000000,-0.038342
J,-0.037960,-0.029974,-0.020846,-0.059413,-0.067127,-0.040007,-0.185572,-0.132020,-0.038342,1.000000

##### Now create a strong correlation between two columns:  D = C + noise

In [5]:
#The noise is mean=0 stdDev=1.0
df["D"] = df["C"]+pd.Series([np.random.randn() for x in range(rows)])

# and see if the correlation matrix changed
# "C" and "D" should be about 0.75
df.corr()

,A,B,C,D,E,F,G,H,I,J
A,1.000000,0.055498,0.143128,-0.002738,-0.104172,0.133259,-0.054147,0.232755,-0.055202,-0.037960
B,0.055498,1.000000,0.079135,0.119405,0.000851,-0.046927,-0.066417,0.199712,0.019713,-0.029974
C,0.143128,0.079135,1.000000,0.667848,-0.024601,0.039943,0.115229,-0.007398,-0.005359,-0.020846
D,-0.002738,0.119405,0.667848,1.000000,0.045299,0.064773,0.042606,-0.022388,0.064807,-0.049388
E,-0.104172,0.000851,-0.024601,0.045299,1.000000,-0.016798,-0.059044,0.016423,0.092680,-0.067127
F,0.133259,-0.046927,0.039943,0.064773,-0.016798,1.000000,0.066916,-0.095933,-0.172330,-0.040007
G,-0.054147,-0.066417,0.115229,0.042606,-0.059044,0.066916,1.000000,0.027569,0.098738,-0.185572
H,0.232755,0.199712,-0.007398,-0.022388,0.016423,-0.095933,0.027569,1.000000,0.079860,-0.132020
I,-0.055202,0.019713,-0.005359,0.064807,0.092680,-0.172330,0.098738,0.079860,1.000000,-0.038342
J,-0.037960,-0.029974,-0.020846,-0.049388,-0.067127,-0.040007,-0.185572,-0.132020,-0.038342,1.000000

In [6]:
from factor_analyzer import FactorAnalyzer

In [7]:
fa = FactorAnalyzer()

In [17]:
fa.analyze(df, 5, rotation=None, use_scaling=False)

In [18]:
fa.loadings

    Factor1   Factor2   Factor3   Factor4   Factor5
A  0.114184  0.034997 -0.084953  0.380798 -0.271002
B  0.102736 -0.149329 -0.026050  0.208505  0.057186
C  0.791289 -0.171112 -0.100211 -0.040721 -0.172196
D  0.808264 -0.209581 -0.157243 -0.107125  0.159324
E -0.005559 -0.063276 -0.010706 -0.029934  0.332857
F  0.235104  0.870698 -0.356077  0.201553  0.120749
G  0.316964  0.370833  0.865362 -0.090376 -0.049258
H  0.029512 -0.221828  0.195483  0.736190  0.089055
I  0.029261 -0.156210  0.176074 -0.008362  0.195305
J -0.098311 -0.047418 -0.175076 -0.137493 -0.135098

In [14]:
fa.get_uniqueness()

   Uniqueness
A    0.760071
B    0.919723
C    0.303231
D    0.241199
E    0.884161
F    0.004617
G    0.002571
H    0.361802
I    0.905526
J    0.920279