##### Create mapping of Store:OLG

In [1]:
PATH = "/home/tbrownex/data/Hackett/JLP/"

In [2]:
# Wave 1
wave1stores = ["Twickenham", "Banstead","Thame", "Wokingham", "Harrogate"]
wave1LGs = [14,19,20,21,23,31,46,66,83,86,94,95,96,281,283,311,370,451,452,455,492],\
[17,327,283,19,281,451,452,83,33,25,36,65,66,54,46,21,23,31,86,37,94,38,14,96,41,95,20],\
[17,19,327,370,283,307,280,281,451,448,425,452,83,66,14,20,65,46,21,23,31,86,96,47,95,218],\
[281,283,335,370,19,45,353,310,342,452,451,455,23,14,95,21,31,94,96,20,36,65,93,66,76],\
[327,280,283,281,19,311,353,355,452,451,54,96,95,36,66,20,25,21,23,31,86,14,223]

In [3]:
# Wave 2
wave2stores = ["Chandlers Ford", "Sidmouth", "Barry", "Westbury Park", "Monmouth"]
wave2LGs = [281,283,280,11,318,327,322,380,370,17,19,307,311,313,335,387,350,425,451,452,20,96,36,14,23,31,66,33],\
[19,283,281,280,311,342,451,452,448,83,20,86,21,65,46,14,96,36,25],\
[280,318,283,370,281,327,335,19,311,387,380,45,350,342,17,313,455,453,448,451,492,425,491,452,81,86,21,96,54,15,23,76],\
[318,327,283,280,17,370,45,19,281,342,427,451,492,452,83,13,33,36,65,46,21,23,93,31,86,37,94,14,96,41,47,95,20],\
[19,378,283,327,489,280,311,281,313,455,448,425,451,452,81,83,20,14,31,96,65,492,36,46,21,23,86,47]

In [4]:
with open(PATH+"mapStore-LG.csv", "w") as output:
    # wave1
    for idx in range(len(wave1stores)):
        lg = ",".join(([str(x) for x in wave1LGs[idx]]))
        rec = wave1stores[idx]+","+ lg +"\n"
        output.write(rec)
    # wave1
    for idx in range(len(wave2stores)):
        lg = ",".join(([str(x) for x in wave2LGs[idx]]))
        rec = wave2stores[idx]+","+ lg +"\n"
        output.write(rec)

In [8]:
with open(PATH+"mapStore-LG.csv", "r") as mapping:
    for rec in mapping:
        rec = rec.rstrip()
        d = {}
        fields = rec.split(",")
        d[fields[0]]= fields[1:]   # First entry holds the store; rest are LGs
        print(d)

{'Twickenham': ['14', '19', '20', '21', '23', '31', '46', '66', '83', '86', '94', '95', '96', '281', '283', '311', '370', '451', '452', '455', '492']}
{'Banstead': ['17', '327', '283', '19', '281', '451', '452', '83', '33', '25', '36', '65', '66', '54', '46', '21', '23', '31', '86', '37', '94', '38', '14', '96', '41', '95', '20']}
{'Thame': ['17', '19', '327', '370', '283', '307', '280', '281', '451', '448', '425', '452', '83', '66', '14', '20', '65', '46', '21', '23', '31', '86', '96', '47', '95', '218']}
{'Wokingham': ['281', '283', '335', '370', '19', '45', '353', '310', '342', '452', '451', '455', '23', '14', '95', '21', '31', '94', '96', '20', '36', '65', '93', '66', '76']}
{'Harrogate': ['327', '280', '283', '281', '19', '311', '353', '355', '452', '451', '54', '96', '95', '36', '66', '20', '25', '21', '23', '31', '86', '14', '223']}
{'Chandlers Ford': ['281', '283', '280', '11', '318', '327', '322', '380', '370', '17', '19', '307', '311', '313', '335', '387', '350', '425', '451', '452', '20', '96', '36', '14', '23', '31', '66', '33']}
{'Sidmouth': ['19', '283', '281', '280', '311', '342', '451', '452', '448', '83', '20', '86', '21', '65', '46', '14', '96', '36', '25']}
{'Barry': ['280', '318', '283', '370', '281', '327', '335', '19', '311', '387', '380', '45', '350', '342', '17', '313', '455', '453', '448', '451', '492', '425', '491', '452', '81', '86', '21', '96', '54', '15', '23', '76']}
{'Westbury Park': ['318', '327', '283', '280', '17', '370', '45', '19', '281', '342', '427', '451', '492', '452', '83', '13', '33', '36', '65', '46', '21', '23', '93', '31', '86', '37', '94', '14', '96', '41', '47', '95', '20']}
{'Monmouth': ['19', '378', '283', '327', '489', '280', '311', '281', '313', '455', '448', '425', '451', '452', '81', '83', '20', '14', '31', '96', '65', '492', '36', '46', '21', '23', '86', '47']}