In [2]:
df = pd.read_csv("/home/tbrownex/data/Hackett/demos/HR/data.csv")

In [5]:
tm.N = 10
tm.K = 4

In [6]:
df = tm.makeDataFrame()

In [8]:
df["A"] = [x for x in range(10)]

In [29]:
df = pd.read_csv("/home/tbrownex/RFscores.csv")

In [16]:
df.corr()

,trees,nodeSize,depth,leafSize,features,MAPE,RMSE
trees,1.000000e+00,2.021433e-17,1.323339e-16,-2.297084e-18,1.435677e-17,-0.011636,-0.005836
nodeSize,2.021433e-17,1.000000e+00,0.000000e+00,0.000000e+00,1.576243e-17,0.023699,0.011887
depth,1.323339e-16,0.000000e+00,1.000000e+00,-1.794596e-18,-2.018921e-17,-0.981299,-0.983717
leafSize,-2.297084e-18,0.000000e+00,-1.794596e-18,1.000000e+00,0.000000e+00,0.023699,0.011712
features,1.435677e-17,1.576243e-17,-2.018921e-17,0.000000e+00,1.000000e+00,-0.005925,0.042828
MAPE,-1.163595e-02,2.369894e-02,-9.812985e-01,2.369894e-02,-5.924736e-03,1.000000,0.995689
RMSE,-5.836386e-03,1.188697e-02,-9.837171e-01,1.171216e-02,4.282805e-02,0.995689,1.000000

In [30]:
df.nsmallest(10, columns="RMSE")

     trees  nodeSize  depth  leafSize  features  MAPE  RMSE
13      90         8     14         4      0.75  0.08  1.04
66     120         8     14         4      0.70  0.08  1.04
67     120         8     14         4      0.75  0.08  1.04
120    150         8     14         4      0.70  0.08  1.04
121    150         8     14         4      0.75  0.08  1.04
12      90         8     14         4      0.70  0.08  1.05
30      90        10     14         4      0.70  0.08  1.05
31      90        10     14         4      0.75  0.08  1.05
84     120        10     14         4      0.70  0.08  1.05
85     120        10     14         4      0.75  0.08  1.05

In [26]:
df.nlargest(10, columns="MAPE")["depth"].mean()

4.0